#!/usr/bin/python

import os
import re
import sys

STATUSES = {
    'A': 'added',
    'D': 'deleted',
    'M': 'modified'
}

DIRECTIONS = {
    'F': 'forward',
    'B': 'backward',
}

def display_status(status):
    return STATUSES.get(status)

def display_direction(direction):
    return DIRECTIONS.get(direction)

class MigrationList(object):

    def __init__(self, items=None):
        if items:
            self.items = items
        self.items = []

    def add(self, migration):
        return self.items.append(migration)

    def remove(self, migration):
        return self.items.remove(migration)

    def plan(self):
        #sorted(self.items, key='migration')
        for item in self.items:
            print item

class Migration(object):

    def __init__(self, app, migration, direction="F", **kwargs):
        self.app = app
        if not direction in DIRECTIONS.keys():
            raise ValueError('Invalid value for direction')
        self.direction = direction
        self.old = kwargs.pop('old', None)
        self.migration = migration
        if self.direction == 'B':
            self.migration = str(int(migration.lstrip('0'))-1).zfill(4)

    def __str__(self):
        return 'migrate %s %s to %s' % (self.app,
                display_direction(self.direction),
                self.migration)

    def migrate(self):
        if self.direction == 'B':
            os.system('git checkout %s %s/migrations' % (self.old, self.app))
        cmd = 'python manage.py migrate %s %s' % (self.app, self.migration)
        print cmd
        os.system(cmd)
        if self.direction == 'B':
            os.system('git reset HEAD %s %s/migrations' % (self.old, self.app))
            os.system('git clean -f %s %s/migrations' %(self.old, self.app))

def main():
    args = sys.argv
    old = args[1]
    new = args[2]

    migrations = MigrationList()

    cmd = 'git diff --name-status %s %s | grep /migrations/' % (
        old, new)
    for line in os.popen(cmd).readlines():
        status, filename = line.split()
        # search for the migration number
        migration_re = re.compile('\d+').search(filename)
        app_re = re.compile('\w+').search(filename)
        if migration_re and app_re:
            if status == 'D':
                direction = 'B'
            else:
                direction = 'F'
            migration = Migration(app_re.group(),
                    migration_re.group(), direction, old=old)
            print migration
            migrations.add(migration)

    #print migrations.plan()

    # TODO: what to do with modified migrations?


if __name__ == '__main__':
    main()
